#!/bin/bash

##
## Make-Make v3
## By Ndr
##

## Make-make, a repo initializer
##    Copyright (C) {2017}  {Ender}

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

REPO='.'
CHOICE=-1

yes_no () {
    local CHOSEN='0'
    local ANSWER
    while [ "$CHOSEN" = '0' ]
    do
	read -p "$1 [Y/N]" -n1 ANSWER
	echo ''
	case $ANSWER in
	    y | Y )
		CHOICE=1
		CHOSEN='1';;
	    n | N )
		CHOICE=0
		CHOSEN='1';;
	    *)
		echo 'Invalid answer, try again.';;
	esac
    done
}

show_help () {
    #Prompting usage
    echo -e "\033[1mUsage: make-make [binary name] [repository name]\033[0m\n"
    echo -e "\033[1m\tbinary name - The name of the make output binary (optional)\033[0m\n"
    echo -e "\033[1m\trepository name - The name of the repo to be created (optional & needs binary name)\033[0m\n"
}

check_args () {
    #Checking arguments
    if test "$#" -ne 1; then
	echo 'You have not specified a valid binary/project name.'
	yes_no "Do you want it to be a.out ?"
	if [ $CHOICE = 1 ];
	then
	    BIN_NAME='a.out'
	else
	    echo -e 'Aborting.'
	    exit
	fi
    else
	if test "$1" -e "-h"; then
	    show_help
	    exit
	fi
	BIN_NAME=$1
    fi
}

create_arbo () {
    #Make arborescence
    mkdir $REPO/lib
    mkdir $REPO/lib/my
    mkdir $REPO/include
    mkdir $REPO/src
    mkdir $REPO/tests
    mkdir $REPO/bonus
}

copy_files () {
    #Copying Makefiles & lib files
    cp ~/bin/make-make_files/Makefile $REPO
    cp ~/bin/make-make_files/main.c $REPO/src
    cp ~/bin/make-make_files/units.c $REPO/tests
    cp ~/bin/make-make_files/make-makelib/Makefile $REPO/lib/my/
    cp ~/bin/make-make_files/make-makelib/*.c $REPO/lib/my/
    cp ~/bin/make-make_files/make-makelib/my.h $REPO/lib/my/
}

change_files () {
    #Modifying main Makefile
    sed -i "s/PROJECTNAME/$BIN_NAME/" $REPO/Makefile
}

auto_commit () {
    yes_no "Do you want to do an initial commit ? (Only works if folder is a git repo)"
    if [ $CHOICE = 1 ];
    then
	cd $REPO
	git add --all
	git commit -m "Initial commit"
	git push origin master
    fi
}

auto_open_main () {
    yes_no "Do you want to open main.c now ? (with $MKEDITOR)"
    if [ $CHOICE = 1 ];
    then
	$MKEDITOR $REPO/src/main.c &
    fi
}

echo -e "\033[1m\033[34mMake-make v3.5: A repo initializer| by Ndr\033[0m\n"
echo -e "\033[1m\033For help, see -h\033[0m\n"
sleep 1s
check_args "$@"
create_arbo
copy_files
change_files
auto_commit
auto_open_main
echo -e "\033[1m\033[36mDone. Have a nice day.\033[0m"
